"""MediaPipe pose landmark names and drawing connections."""

POSE_LANDMARKS = {
    0: "nose",
    1: "left_eye_inner",
    2: "left_eye",
    3: "left_eye_outer",
    4: "right_eye_inner",
    5: "right_eye",
    6: "right_eye_outer",
    7: "left_ear",
    8: "right_ear",
    9: "mouth_left",
    10: "mouth_right",
    11: "left_shoulder",
    12: "right_shoulder",
    13: "left_elbow",
    14: "right_elbow",
    15: "left_wrist",
    16: "right_wrist",
    17: "left_pinky",
    18: "right_pinky",
    19: "left_index",
    20: "right_index",
    21: "left_thumb",
    22: "right_thumb",
    23: "left_hip",
    24: "right_hip",
    25: "left_knee",
    26: "right_knee",
    27: "left_ankle",
    28: "right_ankle",
    29: "left_heel",
    30: "right_heel",
    31: "left_foot_index",
    32: "right_foot_index",
}

LANDMARK_IDS = {name: idx for idx, name in POSE_LANDMARKS.items()}

POSE_CONNECTIONS = [
    (11, 12),
    (11, 13),
    (13, 15),
    (15, 17),
    (15, 19),
    (15, 21),
    (12, 14),
    (14, 16),
    (16, 18),
    (16, 20),
    (16, 22),
    (11, 23),
    (12, 24),
    (23, 24),
    (23, 25),
    (25, 27),
    (27, 29),
    (27, 31),
    (24, 26),
    (26, 28),
    (28, 30),
    (28, 32),
]

SIDE_LANDMARKS = {
    "left": {
        "shoulder": LANDMARK_IDS["left_shoulder"],
        "elbow": LANDMARK_IDS["left_elbow"],
        "wrist": LANDMARK_IDS["left_wrist"],
        "hip": LANDMARK_IDS["left_hip"],
        "knee": LANDMARK_IDS["left_knee"],
        "ankle": LANDMARK_IDS["left_ankle"],
    },
    "right": {
        "shoulder": LANDMARK_IDS["right_shoulder"],
        "elbow": LANDMARK_IDS["right_elbow"],
        "wrist": LANDMARK_IDS["right_wrist"],
        "hip": LANDMARK_IDS["right_hip"],
        "knee": LANDMARK_IDS["right_knee"],
        "ankle": LANDMARK_IDS["right_ankle"],
    },
}
